// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations/CLI use the DIRECT (unpooled) Neon connection.
    // Runtime queries go through the pooled DATABASE_URL via the Neon adapter (src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
