// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load the Next.js-style env file (no plain .env in this repo). On Vercel/CI the
// real env vars already exist and dotenv never overrides them.
import { config } from "dotenv";
config({ path: `.env.${process.env.NODE_ENV ?? "development"}` });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx --conditions react-server prisma/demo-user-seed.ts",
  },
  datasource: {
    // Migrations/CLI use the DIRECT (unpooled) Neon connection.
    // Runtime queries go through the pooled DATABASE_URL via the Neon adapter (src/lib/prisma.ts).
    url: process.env["DIRECT_URL"],
  },
});
